### ISSUE TITLE
Implement bootstrap

### ISSUE THREAD

**Issue by reelode** [emapopa/It-conslut#4]

**Comment by SuperNorvi** [comment]
Vi behöver först gå igenom bootstrap för att kunna applicera det! Vi är ju inte kunniga inom området! xD

**Comment by reelode** [comment]
> Vi behöver först gå igenom bootstrap för att kunna applicera det! Vi är ju inte kunniga inom området! xD

Hi there Roland, Björn has teached us bootstrap in one of our lectures, so please implement Bootstrap.
